ProjectBoots2/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectBoots2.Models;
using ProjectBoots2.Models.contexts;
using static System.Net.Mime.MediaTypeNames;
using System.Security.Cryptography;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using ProjectBoots2.Controllers.Admin;

namespace ProjectBoots2.Controllers
{
    //[LoginAttribute]
    public class AdminController : Controller
    {
        dbBootsContext context = new dbBootsContext();
        CategoryRepo categoryRepo = new CategoryRepo();

        AdminAdminController AdminAdminController = new AdminAdminController();
        AdminCategoryController AdminCategoryController = new AdminCategoryController();
        AdminProductController AdminProductController = new AdminProductController();

        public IActionResult Index()
        {
            this.ViewBag.Admins = context.Administrators;
            this.ViewBag.Products = context.Products;
            this.ViewBag.Categories = categoryRepo.Categories.Where(cat => cat.Id != 0);
            this.ViewBag.Orders = context.Orders;
            return View();
        }

        /* ADMIN */
        public IActionResult ModifyAdmin(int id)
        {
            return AdminAdminController.ModifyAdmin(id);
        }

        [HttpPost]
        public IActionResult ModifyAdmin(Administrator admin)
        {
            return AdminAdminController.ModifyAdmin(admin);
        }

        public IActionResult DelAdmin(int id)
        {
            return AdminAdminController.DelAdmin(id);
        }

        /* CATEGORY */
        public IActionResult ModifyCategory(int id)
        {
            return AdminCategoryController.ModifyCategory(id);
        }

        [HttpPost]
        public IActionResult ModifyCategory(Category category)
        {
            return AdminCategoryController.ModifyCategory(category);
        }

        public IActionResult DelCategory(int id)
        {
            return AdminCategoryController.DelCategory(id);
        }

        /* PRODUCT */
        [HttpGet]
        public IActionResult ModifyProduct(int id)
        {
            return AdminProductController.ModifyProduct(id);
        }

        [HttpPost]
        public IActionResult ModifyProduct(ProductFormModel productModel)
        {
            return AdminProductController.ModifyProduct(productModel);
        }

        public IActionResult DelProduct(int id)
        {
            return AdminProductController.DelProduct(id);
        }

        public IActionResult ModifyVariation(int id)
        {
            return AdminProductController.ModifyVariation(id);
        }

        [HttpPost]
        public IActionResult ModifyVariation(Variation variation)
        {
            return AdminProductController.ModifyVariation(variation);
        }

        /* order */
        public IActionResult Order(int id)
        {
            ViewBag.Order = context.Orders.Find(id);
            List<OrderItem> orderItems = context.OrderItems.Where(item => item.OrderId == id).ToList();
            foreach(OrderItem item in orderItems)
                item.Variation = context.Variations.AsNoTracking().First(vrt => vrt.Id == item.VariationId);

            ViewBag.OrderItems = orderItems;
            return View();
        }

        public IActionResult CheckOrder(int id)
        {
            Order order = context.Orders.Find(id);
            order.Finished = !order.Finished;

            return RedirectToAction("Index");
        }
    }
}

ProjectBoots2/Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectBoots2.Models;
using ProjectBoots2.Models.contexts;
using System.Text.Json;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Model;

namespace ProjectBoots2.Controllers
{
    public class CheckoutController : Controller
    {
        dbBootsContext context = new dbBootsContext();

        private void LoadCart()
        {
            string? jsonString = HttpContext.Session.GetString("cart");
            if (jsonString == null) return;

            List<CartItem> cartItems = JsonSerializer.Deserialize<List<CartItem>>(jsonString);
            if (cartItems.Count <= 0) return;

            List<OrderItem> orderItems = new List<OrderItem>();
            int? total = 0;
            foreach (CartItem item in cartItems)
            {
                if (item.Amount == 0) continue;
                Variation variation = context.Variations.First(vrt => vrt.Id == item.VariationId);
                variation.Product = context.Products.First(prd => prd.Id == variation.ProductId);
                variation.Product.ProductImages = new List<ProductImage>();
                variation.Product.ProductImages.Add(context.ProductImages.First(img => img.ProductId == variation.ProductId));

                OrderItem orderItem = new OrderItem();
                orderItem.Variation = variation;
                orderItem.Quantity = item.Amount;
                orderItem.Price = item.Amount * (variation.SalePrice != 0 ? variation.SalePrice : variation.Price);
                total += orderItem.Price;
                orderItems.Add(orderItem);
            }

            TempData["orderItems"] = orderItems;
            TempData["total"] = total;
        }

        private Order GetOrder()
        {
            Order order = new Order();

            try { order = JsonSerializer.Deserialize<Order>(HttpContext.Session.GetString("order")); }
            catch { }

            return order;
        }

        private void SetOrder(Order order)
        {
            string jsonString = JsonSerializer.Serialize(order);
            HttpContext.Session.SetString("order", jsonString);
        }

        public IActionResult Cart()
        {
            LoadCart();
            return View();
        }

        public IActionResult CartAmount(int vrtId, int amount)
        {
            List<CartItem> cartItems = JsonSerializer.Deserialize<List<CartItem>>(HttpContext.Session.GetString("cart"));
            CartItem cartItem = cartItems.First(item => item.VariationId == vrtId);
            //Variation variation = context.Variations.Find(vrtId);
            //if (variation.InStock < amount) amount = (int)variation.InStock;
            cartItem.Amount = amount;
            HttpContext.Session.SetString("cart", JsonSerializer.Serialize(cartItems));

            return RedirectToAction("Cart");
        }

        public IActionResult CartClear()
        {
            HttpContext.Session.Remove("cart");
            return RedirectToAction("Cart");
        }

        [HttpGet]
        public IActionResult Information()
        {
            Order order = GetOrder();
            LoadCart();
            return View(order);
        }

        [HttpPost]
        public IActionResult PostInformation(Order order)
        {
            SetOrder(order);
            return RedirectToAction("Shipping");
        }

        [HttpGet]
        public IActionResult Shipping()
        {
            Order order = GetOrder();
            LoadCart();
            return View(order);
        }

        [HttpPost]
        public IActionResult PostShipping(Order order)
        {
            SetOrder(order);
            return RedirectToAction("Payment");
        }

        [HttpGet]
        public IActionResult Payment()
        {
            Order order = GetOrder();
            LoadCart();
            return View(order);
        }

        [HttpPost]
        public IActionResult PostPayment(Order order)
        {
            context.Orders.Add(order);
            context.SaveChanges();
            
            int orderId = order.Id;

            //if (!ModelState.IsValid) return RedirectToAction("Information");

            return RedirectToAction("Confirm", new { id = orderId });
        }

        public IActionResult Confirm(int id)
        {
            Order order = context.Orders.Find(id);
            ViewBag.Order = order;
            LoadCart();

            string? jsonString = HttpContext.Session.GetString("cart");
            List<CartItem> cartItems = JsonSerializer.Deserialize<List<CartItem>>(jsonString);

            List<OrderItem> orderItems = new List<OrderItem>();
            foreach(CartItem item in cartItems)
            {
                if (item.Amount == 0) continue;
                OrderItem orderItem = new OrderItem();
                Variation variation = context.Variations.First(vrt => vrt.Id == item.VariationId);

                orderItem.VariationId = item.VariationId;
                orderItem.Price = variation.SalePrice != 0 ? variation.SalePrice : variation.Price;
                orderItem.Quantity = item.Amount;
                orderItem.OrderId = id;

                variation.InStock -= item.Amount;

                context.OrderItems.Add(orderItem);
                context.SaveChanges();
            }

            HttpContext.Session.Remove("cart");
            HttpContext.Session.Remove("order");
            return View();
        }
    }
}

ProjectBoots2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectBoots2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectBoots2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectBoots2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProjectBoots2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjectBoots2/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectBoots2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectBoots2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div>
                    <a asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="https://www.linkpicture.com/q/Group-4_2.png" alt="logo boty.cz" height="30px"/>
                    </a>

                    <a class="navbar-brand ms-4" asp-area="" asp-controller="Admin" asp-action="Index">Administráční panel</a>
                </div>

                <div class="text-end">
                    <a asp-controller="Login" asp-action="Logout">
                        <button class="btn btn-primary" type="button">Odhlásit</button>
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProjectBoots2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" type="text/css" href="extensions/filter-control/bootstrap-table-filter-control.css">
    <script src="extensions/filter-control/bootstrap-table-filter-control.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjectBoots2/Views/Shared/_LayoutBoots.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Boty.cz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/GlobalStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/FooterStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/HeaderStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/CssVariables.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectBoots2.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="mobile-hidden"><div>&nbsp</div></header>
    <header>
        <section class="top">
            <img src="~/img/8.svg" alt="contact icon" class="contact-icon">
            <a href="tel:+420777666555" class="phone-number">
                <span class="phone-prefix">+420 </span>777 666 555
            </a>
            <p class="divider">|</p>
            <a href="mailto:info@nejlepsiboty.cz" class="mail">info@nejlepsiboty.cz</a>
            <img src="~/img/profile-user.svg" alt="profile icon" class="profile-icon">
            <a href="" class="sign-in">Přihlásit se</a>
        </section>

        <aside>
            <header>
                <a asp-controller="Home" asp-action="Index">
                    <img src="~/img/Group%204.svg" alt="Boty logo" class="boty-logo">
                </a>
                <div class="search-input">
                    <img src="~/img/loupe.svg" height="16" alt="search icon">
                    <form action="search.php" id="search-form">
                        <input type="search" name="search" placeholder="Vyhledat zboží..." class="search-input">
                    </form>
                    <script>
                        const node = document.getElementsByClassName("search-input")[0];
                        node.addEventListener("keyup", ({key}) => {
                            if (key === "Enter") {
                                document.getElementById("search-form").submit();
                            }
                        })
                    </script>
                </div>
                <img src="~/img/loupe.svg" alt="search icon" class="search-icon">
                <a asp-controller="Checkout" asp-action="Cart">
                    <img src="~/img/Group%206.png" alt="basket icon" class="basket-icon">
                </a>
                <img src="~/img/heart.svg" alt="favorite icon" class="fav-icon">
            </header>
            <nav>
                <a href="">
                    <div>
                        Chlapecké
                        <img src="~/img/Group%20169.svg" alt="man icon" class="man-icon">
                    </div>
                </a>
                <a href="">
                    <div>
                        Dívčí
                        <img src="~/img/Group%20171.svg" alt="man icon" class="woman-icon">
                    </div>
                </a>
                <a href=""><div>Doplňky</div></a>
                <a href=""><div>Ostatní</div></a>
                <a href=""><div class="contact">Kontakt</div></a>
            </nav>
        </aside>
    </header>
    <header class="mobile-hidden"><div>&nbsp</div></header>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    
    <footer>
        <section class="subscribtion">
            <form action="newsletter.php">
                <h2>Nezmeškejte nové výhodné akce</h2>
                <p>Zadejte svůj e-mail a obratem vám zašleme PDF s inpirací zdarma.</p>
                <div>
                    <img src="~/img/6.svg" alt="e-mail icon">
                    <input type="email" name="email" placeholder="Zadej svůj mail..." required>
                    <button class="primary-button" type="submit">Přihlásit</button>
                </div>
            </form>
        </section>

        <section class="bottom">
            <div class="right">
                <h3 class="about-title">O nás</h3>
                <p class="about-descriptio">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A adipisci autem fuga minima molestias mollitia perspiciatis, veniam vero? Accusantium amet earum eligendi eum ipsam ipsum pariatur, velit. Adipisci, aliquid odio?</p>
                <h3 class="links-title">Naše nabídka</h3>
                <div class="links-girls">
                    <h4><a href="">Dívčí</a></h4>
                    <ul>
                        <li><a href="">Tenisky</a></li>
                        <li><a href="">Holinky</a></li>
                        <li><a href="">Sandály</a></li>
                        <li><a href="">Baleríny</a></li>
                        <li><a href="">Polobotky</a></li>
                    </ul>
                </div>
                <div class="links-boys">
                    <h4><a href="">Chlapecké</a></h4>
                    <ul>
                        <li><a href="">Tenisky</a></li>
                        <li><a href="">Holinky</a></li>
                        <li><a href="">Sandály</a></li>
                        <li><a href="">Baleríny</a></li>
                        <li><a href="">Polobotky</a></li>
                    </ul>
                </div>
                <a asp-controller="Home" asp-action="Index">
                    <img src="~/img/Group%204.svg" alt="boty logo" class="logo">
                </a>
            </div>
            <div class="left">
                <h4>Kontaktujte nás</h4>
                <div>
                    <a href="mailto:info@nejlepsiboty.cz">
                        <img src="~/img/6.svg" alt="mail icon">
                        info@nejlepsiboty.cz
                    </a>
                </div>
                <div>
                    <a href="tel:+420777666555">
                        <img src="~/img/8.svg" alt="phone icon">
                        +420 777 666 555
                    </a>
                </div>
                <div>
                    <a href=""><img src="~/img/facebook.png" alt="facebook icon"></a>
                    <a href=""><img src="~/img/Group%20153.svg" alt="instagram icon"></a>
                    <a href=""><img src="~/img/twitter.svg" alt="twitter icon"></a>
                </div>
                <address>
                    <a href="http://maps.google.com/?q=1200 Litvínovská 600, Praha 9, 190 00">
                        Litvínovská 600, Praha 9, 190 00
                    </a>
                </address>
            </div>
        </section>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" type="text/css" href="extensions/filter-control/bootstrap-table-filter-control.css">
    <script src="extensions/filter-control/bootstrap-table-filter-control.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjectBoots2/Views/Shared/_LayoutCheckout.cshtml
@{
    Layout = "_LayoutBoots";
}

@if(@ViewContext.RouteData.Values["action"].ToString() != "Confirm"){
    <section class="category-path mb-5">
        <a asp-controller="Checkout" asp-action="Cart">Košík > </a>
        <a asp-controller="Checkout" asp-action="Information" class="@(@ViewContext.RouteData.Values["action"].ToString() == "Information" ? "fw-bold" : "")">Údaje > </a>
        <a asp-controller="Checkout" asp-action="Shipping" class="@(@ViewContext.RouteData.Values["action"].ToString() == "Shipping" ? "fw-bold" : "")">Pošta > </a>
        <a asp-controller="Checkout" asp-action="Payment" class="@(@ViewContext.RouteData.Values["action"].ToString() == "Payment" ? "fw-bold" : "")">Platba</a>
    </section>
}

<div class="row">
    <div class="col">
        @RenderBody()
    </div>
    <div class="col">
        @if (@TempData["orderItems"] != null)
        {
            <table class="table">
                <tbody>
                    @foreach (OrderItem item in (List<OrderItem>)TempData["orderItems"])
                    {
                        <tr>
                            <td>
                                <img width="50px" src="@item.Variation.Product.ProductImages[0].Url" alt="obrázek boty" />
                            </td>
                            <td>@item.Variation.Product.Title <span class="text-secondary">(@item.Variation.Color, @item.Variation.Size)</span></td>
                            <td>@(item.Quantity * (item.Variation.SalePrice != null ? item.Variation.SalePrice : item.Variation.Price)) Kč</td>
                        </tr>
                    }
                </tbody>
            </table>

            <h4 class="text-end fw-bold">Celkem: @TempData["total"]</h4>
        }
    </div>
</div>